### ISSUE TITLE
Frontend to-do's

### ISSUE THREAD

**Issue by rene78** [rene78/Heads-Or-Tails#5]
## UX
- [x] Catch event, when user clicks on _Reject_ in Metamask

- [x] Always convert to Ether/Wei with the web3 functions (e.g. `web3.utils.toWei`). Numbers >10e15 cannot be handled properly by JS.

- [x] For users without web3 browser: load contract data via [`ethers . getDefaultProvider`](https://docs.ethers.io/ethers.js/html/api-providers.html#connecting-to-ethereum) Done (https://github.com/rene78/Heads-Or-Tails/commit/d4592d819aab2daafbd538d1e1fee402ca782996)

- [x] If users deny access to Metamask: Still load contract information via Infura.

## UI
- [x] Improve layout [(Figma)](https://www.figma.com/file/GC69ySjJF2hIWCvfS2X02I/Landing-page?node-id=0%3A1)
- [x] Make stopCoinFlip() wait for promise from stopAnimation()
- [x] After click on Play scroll to coin animation
- [x] Top right infobox
- [x] Shorten contract URL at bottom left and add link to this Github repo
